### ISSUE TITLE
println in macro body causes error

### ISSUE THREAD

**Issue by FalseProtagonist** [basilisp-lang/basilisp#908] opened 2024-07-21 17:31 UTC
if eg. println is called during macro evaluation, seems to cause an error

**Comment by chrisrink10** [comment] 2024-07-22 13:28
Please provide reproduction steps and errors (if any occurred).

**Comment by chrisrink10** [comment] 2024-07-30 19:46
Closing this since there's no repro. Can re-open if we get some steps.

**Closed by chrisrink10** 2024-07-30 19:46 UTC
