### ISSUE TITLE
cli command basilisp test does not work with Python 3.12.7

### ISSUE THREAD

**Issue by ikappaki** [basilisp-lang/basilisp#1119] opened 2024-11-09 12:14 UTC
Hi,

the `basilisp test` cli command does not work with Basilisp 3.12:
```basilisp test: error: the following arguments are required: args```

To reproduce
1. With Python 3.12 as the main interpreter, create a new project with Poetry,  and `basilisp` and `pytest` as dependencies, and `shell` to it
``` ps1
> poetry new issue-test-312
Created package issue_test_312 in issue-test-312
> cd issue-test-312
> poetry add basilisp
Using version ^0.3.0 for basilisp
...
> poetry add pytest
Using version ^8.3.3 for pytest
...
> poetry shell
Spawning shell within D:\rissue-test-312\.venv
...
> python --version
Python 3.12.7
```
2. Run `basilisp test` the error comes up
``` ps1
> basilisp test
usage: basilisp test [-h] [--generate-auto-inlines [GENERATE_AUTO_INLINES]] [--inline-functions [INLINE_FUNCTIONS]]
                     [--warn-on-arity-mismatch [WARN_ON_ARITY_MISMATCH]]
                     [--warn-on-shadowed-name [WARN_ON_SHADOWED_NAME]] [--warn-on-shadowed-var [WARN_ON_SHADOWED_VAR]]
                     [--warn-on-unused-names [WARN_ON_UNUSED_NAMES]]
                     [--warn-on-non-dynamic-set [WARN_ON_NON_DYNAMIC_SET]]
                     [--use-var-indirection [USE_VAR_INDIRECTION]]
                     [--warn-on-var-indirection [WARN_ON_VAR_INDIRECTION]]
                     [--include-unsafe-path [INCLUDE_UNSAFE_PATH]] [-p INCLUDE_PATH]
                     [--data-readers-entry-points [DATA_READERS_ENTRY_POINTS]] [--disable-ns-cache [DISABLE_NS_CACHE]]
                     [--enable-logger [ENABLE_LOGGER]] [-l LOG_LEVEL]
                     [--emit-generated-python [EMIT_GENERATED_PYTHON]]
basilisp test: error: the following arguments are required: args
```

The same works fine on Python 3.11
``` ps1
> python --version
Python 3.11.4
> poetry new issue-test-311
Created package issue_test_311 in issue-test-311
> cd .\issue-test-311\
> poetry add basilisp
Creating virtualenv issue-test-311 in D:\issue-test-311\.venv
Using version ^0.3.0 for basilisp
...
> poetry add pytest
Using version ^8.3.3 for pytest
...
> poetry shell
Spawning shell within D:\removeme\bas\issue-test-311\.venv
...
> basilisp test
================================================= test session starts =================================================
platform win32 -- Python 3.11.4, pytest-8.3.3, pluggy-1.5.0
rootdir: D:\issue-test-311
configfile: pyproject.toml
plugins: basilisp-0.3.0
collected 0 items

================================================== warnings summary ===================================================
.venv\Lib\site-packages\_pytest\config\__init__.py:1277
  D:\issue-test-311\.venv\Lib\site-packages\_pytest\config\__init__.py:1277: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: basilisp
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
================================================= 1 warning in 0.03s ==================================================
```

I had a quick look and it seems possible that the error is caused by the negative argument passed to `nargs` below? I couldn't find anything about negative values in the [argparse nargs section](https://docs.python.org/3/library/argparse.html#nargs) of the python documentation, perhaps that was undocumented behavior that has gone away? Maybe an alternative option would be to use an explicit argument such as `--pytest-args` to signify the arguments to pytest?

basilisp/cli.py
```python
def _add_test_subcommand(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("args", nargs=-1, help="arguments passed on to Pytest")
```

Thanks

**Comment by chrisrink10** [comment] 2024-11-10 19:34
I am unable to reproduce the same on MacOS at least with Python 3.11.7, 3.12.1, or 3.13.0, but I was able to reproduce with specifically the Python 3.12.7 version you were using. I'm looking into this a bit more to see if there was some regression in that version.

**Comment by ikappaki** [comment] 2024-11-11 07:53
> I am unable to reproduce the same on MacOS at least with Python 3.11.7, 3.12.1, or 3.13.0, but I was able to reproduce with specifically the Python 3.12.7 version you were using. I'm looking into this a bit more to see if there was some regression in that version.

Good catch! Version 3.12.7 is the latest 3.12 release, so GH Actions picked it up accordingly when I tried to upgrade to 0.3.0 😅. Thanks for looking into this!

**Comment by chrisrink10** [comment] 2024-11-11 14:40
Were you able to confirm similar findings? Just wondering how widespread the effects here are.

**Comment by ikappaki** [comment] 2024-11-11 19:27
> Were you able to confirm similar findings? Just wondering how widespread the effects here are.

Hi @chrisrink10,

The issue is due to the https://github.com/python/cpython/pull/124631 PR. It is part of the v3.12.7 tag, but hasn't made it to the v3.13.0 release (this is why it's currently working), it is in the latest 3.13 branch and main, so it is going to fail there too when these are released.

I've created a min repo out of `basilisp.cli` to reproduce the issue at https://github.com/ikappaki/issue-cpython-argparse-neg.

Basically I've extracted the relevant cpython/Lib/parsearg.py commits across the different cpython versions, and stored them locally, and reference them from the cli.py file (needs manually commented and uncommented the versions). It can be run with

```shell
> python cli.py test
:1 args ['cli.py', 'test']
usage: cli.py test [-h]
cli.py test: error: the following arguments are required: args
```

the above failure is from the v3.12.7 tag.

I can open an issue with cpypthon, but I couldn't find any documentation what a negative nargs supposed to do. Do you happen to have a pointer somewhere so I can describe the (official) expected behavior?

Thanks

**Comment by ikappaki** [comment] 2024-11-11 22:29
I've updated the repo to the bare minimum repro:

```python
parser = argparse.ArgumentParser()
parser.add_argument("args", nargs=-1, help="extra arguments")
parsed_args, extra = parser.parse_known_args()
print(f":args {parsed_args} :extra {extra}")
```

``` shell
$ python cli.py 2 3
usage: cli.py [-h]
cli.py: error: the following arguments are required: args
```

I noticed that quite a few repos out there using the `nargs=-1` pattern

https://grep.app/search?q=nargs%3D-1&filter[lang][0]=Python

**Comment by chrisrink10** [comment] 2024-11-11 23:17
> I went ahead and raised https://github.com/python/cpython/issues/126708 ...

Thanks for checking that out and submitting the ticket.

**Comment by chrisrink10** [comment] 2024-11-12 01:30
https://github.com/python/cpython/issues/126708#issuecomment-2469299411

It's possible that this comment points to the provenance of this `nargs=-1`. Basilisp did use Click a long time ago and it might've been configured like this and never migrated properly.

**Comment by chrisrink10** [comment] 2024-11-12 01:45
@ikappaki I just tried the change (to using `argparse.REMAINDER`) and that appears to work in 3.11.7, 3.12.7, and 3.13.0. From what I can find in the CPython repository, that `nargs` value isn't without its own issues (and it was indeed removed from the documentation due to those issues) but it seems to at least resolve the immediate issue you reported.

**Comment by chrisrink10** [comment] 2024-11-12 02:16
I merged that down, so hopefully it works. Easy enough to revert or change if not though.

**Closed** 2024-11-13 16:18 UTC
Labels: issue-type:bug, component:cli
